services:
  devcontainer:
    hostname: dev_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    networks:
      - ubuntu_rpi
    command: sleep infinity

  rpi:
    hostname: rpi
    image: ptrsr/pi-ci
    volumes:
      - ../dist:/dist
    restart: unless-stopped
    networks:
      - ubuntu_rpi
      - influx_rpi
    command: start

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=battery_data
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - influx_rpi
      - influx_grafana

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - influx_grafana

networks:
  influx_rpi:
    driver: bridge
  influx_grafana:
    driver: bridge
  ubuntu_rpi:
    driver: bridge

volumes:
  influxdb_data:
  grafana_data: